# Generated by Django 5.2.12 on 2026-03-22 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📅', help_text='Emoji icon', max_length=10)),
                ('color', models.CharField(choices=[('green', 'Green'), ('red', 'Red')], default='green', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('color', models.CharField(choices=[('green', 'Green'), ('red', 'Red')], default='green', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Insight Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsightTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_available_in_nigeria', models.BooleanField(default=True)),
                ('is_available_global', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Tech Workshop'), ('training', 'Corporate Training'), ('webinar', 'Webinar'), ('launch', 'Product Launch'), ('internal', 'Internal Staff Event'), ('conference', 'Conference')], default='webinar', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('past', 'Past')], default='upcoming', max_length=10)),
                ('access', models.CharField(choices=[('all', 'All Users'), ('ng', 'Nigeria Only'), ('global', 'Global Only')], default='all', help_text='Who sees this event based on geo', max_length=10)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical address or "Online"', max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('timezone_label', models.CharField(default='WAT', help_text='e.g. WAT, GMT, EST', max_length=40)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('banner_image', models.ImageField(blank=True, help_text='Wide banner for hero section', null=True, upload_to='events/banners/')),
                ('video_recap', models.URLField(blank=True, help_text='YouTube embed URL for past event recap')),
                ('registration_url', models.URLField(blank=True, help_text='External Zoom/Eventbrite link')),
                ('is_free', models.BooleanField(default=True)),
                ('price_ng', models.DecimalField(blank=True, decimal_places=2, help_text='Price in NGN (₦)', max_digits=10, null=True)),
                ('price_global', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD ($)', max_digits=10, null=True)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('partners_count', models.PositiveIntegerField(default=0)),
                ('speakers_count', models.PositiveIntegerField(default=0)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured hero section')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventcategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. CEO, Tranter IT', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/speakers/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='core.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. CTO, Zenith Bank', max_length=150)),
                ('quote', models.TextField(max_length=400)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='1–5 stars')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Leave blank to show on all events page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('insight_type', models.CharField(choices=[('article', 'Article'), ('report', 'Report (PDF)'), ('video', 'Video'), ('dashboard', 'KPI Dashboard'), ('sponsored', 'Sponsored / Premium')], default='article', max_length=12)),
                ('audience', models.CharField(choices=[('all', 'All'), ('ng', 'Nigeria Only'), ('global', 'Global Only')], default='all', max_length=8)),
                ('excerpt', models.TextField(max_length=320)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='insights/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed URL')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='insights/pdfs/')),
                ('pdf_label', models.CharField(blank=True, default='Download Report', max_length=120)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('author_role', models.CharField(blank=True, max_length=120)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='insights/authors/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Minutes')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=320)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='core.insightcategory')),
                ('tags', models.ManyToManyField(blank=True, to='core.insighttag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
