# Generated by Django 5.2.12 on 2026-03-22 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier for this content block (e.g., 'hero_section', 'pricing_banner')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this content block', max_length=200)),
                ('nigeria_text', models.TextField(blank=True, help_text='Text content for Nigerian users')),
                ('nigeria_image', models.ImageField(blank=True, help_text='Image for Nigerian users', null=True, upload_to='content/nigeria/')),
                ('nigeria_json', models.JSONField(blank=True, help_text='Structured data for Nigerian users (e.g., pricing, features)', null=True)),
                ('global_text', models.TextField(blank=True, help_text='Text content for global (non-Nigerian) users')),
                ('global_image', models.ImageField(blank=True, help_text='Image for global users', null=True, upload_to='content/global/')),
                ('global_json', models.JSONField(blank=True, help_text='Structured data for global users (e.g., pricing, features)', null=True)),
                ('nigeria_currency_code', models.CharField(default='NGN', help_text='Currency code for Nigeria (e.g., NGN)', max_length=3)),
                ('nigeria_currency_symbol', models.CharField(default='₦', help_text='Currency symbol for Nigeria', max_length=10)),
                ('global_currency_code', models.CharField(default='USD', help_text='Currency code for Global (e.g., USD)', max_length=3)),
                ('global_currency_symbol', models.CharField(default='$', help_text='Currency symbol for Global', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active blocks are returned by get_content()')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='geo_content_key_9deff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detected_country', models.CharField(blank=True, max_length=2)),
                ('selected_region', models.CharField(choices=[('NG', 'Nigeria'), ('GLOBAL', 'Global')], max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Region Switch Log',
                'verbose_name_plural': 'Region Switch Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
