# Generated by Django 5.2.12 on 2026-03-22 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_badge_notificationpreference_userbadge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signal_type', models.CharField(choices=[('task_request', '📋 Task Request'), ('reminder', '⏰ Reminder'), ('priority', '🔥 Priority Alert'), ('attention', '👀 Needs Attention'), ('help_needed', '🆘 Help Needed'), ('question', '❓ Question'), ('update', '📢 Update'), ('acknowledgment', '✅ Acknowledgment')], max_length=30)),
                ('subject_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('default_urgency', models.CharField(choices=[('low', 'Low - When you have time'), ('normal', 'Normal - Today'), ('high', 'High - Next few hours'), ('urgent', 'Urgent - ASAP')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('task_request', '📋 Task Request'), ('reminder', '⏰ Reminder'), ('priority', '🔥 Priority Alert'), ('attention', '👀 Needs Attention'), ('help_needed', '🆘 Help Needed'), ('question', '❓ Question'), ('update', '📢 Update'), ('acknowledgment', '✅ Acknowledgment')], max_length=30)),
                ('urgency', models.CharField(choices=[('low', 'Low - When you have time'), ('normal', 'Normal - Today'), ('high', 'High - Next few hours'), ('urgent', 'Urgent - ASAP')], default='normal', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, choices=[('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('❤️', 'Love'), ('🔥', 'Fire'), ('✅', 'Done')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='dashboard.project')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='dashboard.task')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='dashboard_s_recipie_f86ffb_idx'), models.Index(fields=['sender', 'created_at'], name='dashboard_s_sender__83adac_idx'), models.Index(fields=['signal_type', 'urgency'], name='dashboard_s_signal__2ff33f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignalMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'muted_user')},
            },
        ),
    ]
